config/routes.rb
Rails.application.routes.draw do
  root 'page#index'

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'

  get '/about' => 'page#about'

  get '/contact' => 'page#contact'

  get '/faqs' => 'page#faqs'

  get '/privacy' => 'page#privacy'

  get '/terms' => 'page#terms'

  get '/Admin' => 'user#admin_login'
  get '/logout' => 'user#logout'

  resources :products

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
layout 'cart'
def add
  # get the ID of the product
  id = params[:id]
    # if the cart has already been created, use the existing cart else create a new cart
    if session[:cart] then
       cart = session[:cart]
    else
       session[:cart] = {}
       cart = session[:cart]
    end
    # if the product has alreadd been added to the cart, increment the value else set the value to 1
    if cart[id] then
       cart[id] = cart[id] + 1
    else
       cart[id] = 1
    end
# redirect to the cart display page
  redirect_to :action => :index
end #end add method

def clearCart
# set the session variable to nil and redirect
   session[:cart] = nil
   
   session[:items_in_cart] = 0
   session[:total_amount] = '0.00'

   redirect_to :action => :index
end

def index
# if there is a cart, pass it to the page for display else pass an empty value
  if session[:cart] then
    @cart = session[:cart]
  else
    @cart = {}
  end
end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
 layout 'page'
  def index
  end
  
  def about
  end

  def contact
  end

  def faqs
  end

  def privacy
  end

  def terms
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  layout 'products'
  # GET /products
  def index
    @products = Product.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category, :subcategory, :brand)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<% total = 0 %>
<% items = 0 %>
<% @cart.each do | id, quantity | %>
	<% product = Product.find_by_id(id) %>
	<tr>
	<td>
	<div class="image">
	<%= link_to (image_tag product.image_url, :style => "height:40px"), product %>
	</div>
	</td>
	<td class="title"><%= link_to product.title, product %></td>
	<td class="price"><%= number_to_currency(product.price) %></td>
	<td class="quantity"><%= quantity %><br /></td>
	<td class="price">
	<%= number_to_currency(quantity * product.price, :unit => "€") %>
	</td>
	</tr>
	<% total += quantity * product.price %>
	<% items += quantity  %>
	<% session[:total_amount] = total %>
	<% session[:items_in_cart] =items %>
<% end %>

<br />
<br />
<br />
<br />
<h1><%= @itemd %></h1>

<div id="cart_wrap">
	<h1>SHOPPING CART</h1>
	<ul id="product_nav">
		<li><a href=""></i>HOME</a></li>
		<li><a href="">WOMEN</a></li>
		<li><a href="">MEN</a></li>
		<li><a href="">BLOG</a></li>
		<li id="searc">
			SEARCH <i class="fa fa-book fa-lg"></i>
		</li>
	</ul>
	<h2>YOUR SHOPPING BAG</h2>
	<div id="left">
	<div id="cart_products">
		<p id="its">ITMES (<%= items %>)<a href="<%=cart_clear_path%>">CLEAR BAG <i class="fa fa-trash-o"></i></a></p>
	</div>
		<% if @cart.empty? %><p id="empty_lab"><i class="fa fa-info-circle fa-lg"></i> Your shopping bag currently is empty.</p><% end %>

		<ul id="c_products">
			<% @cart.each do | id, quantity | %>
			<% product = Product.find_by_id(id) %>
			<li>
				<div id="cart_img"></div>
				<h3><%= link_to product.title, product %></h3>
				<span><%= number_to_currency(total, :unit => "€") %></span>
				<p>
					Item B9262<br />
					Size: X-SMALL<br />
					Color: BLUE GROTTO<br />
				</p>
			</li>
			<% end %>
		</ul>
		<%= link_to 'Continue Shopping', :controller => :products %>

	</div><!--left -->


	<div id="checkout">
		<h3>SUMMARY</h3>
		<strong><p>SUBTOTAL<span><%= number_to_currency(total, :unit => "€") %></span></p></strong>
		<p>Duties<span>0</span></p>
		<p>Shipping<span>0</span></p>
		<p>Discount<span>0</span></p>
		<p>Tax<span>0</span></p>
		<h3 id="total">TOTAL<span><%= number_to_currency(total, :unit => "€") %></span></h3>
		<a href="">CHECK OUT NOW</a>
	</div>


</div><!--cart_wrap-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/navigation' %>
<%= yield %>
<%= render 'partials/footer' %>
</body>
</html>

app/views/layouts/cart.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'cart', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'cart', 'data-turbolinks-track' => true %>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/navigation' %>
<%= yield %>
<%= render 'partials/footer' %>
</body>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'page', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'products', 'data-turbolinks-track' => true %>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/navigation' %>
<div id="main_wrap">
	<%= yield %>
</div>
<%= render 'partials/footer' %>
</body>
</html>

app/views/layouts/products.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= stylesheet_link_tag    'products', media: 'all', 'data-turbolinks-track' => true %>
  <%#= javascript_include_tag 'products', 'data-turbolinks-track' => true %>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'partials/navigation' %>
<%= yield %>
<%= render 'partials/footer' %>
</body>
</html>

app/views/page/about.html.erb
<br />
<br />
<br />
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

app/views/page/contact.html.erb
<h1>Page#contact</h1>
<p>Find me in app/views/page/contact.html.erb</p>

app/views/page/faqs.html.erb
<h1>Page#faqs</h1>
<p>Find me in app/views/page/faqs.html.erb</p>

app/views/page/privacy.html.erb
<h1>Page#privacy</h1>
<p>Find me in app/views/page/privacy.html.erb</p>

app/views/page/terms.html.erb
<div id="terms">
<h1>GENERAL TERMS AND CONDITIONS</h1>
<p>
Welcome to TopStore Web Site ('Site '). Please review the following basic terms that govern your use of and purchase of products from our Site. These terms rule all purchases that are made by consumers through the online-shop of TopStore.
</p>
<h3>GENERAL</h3>
<p>
You may purchase retail products by using this Site. We may from time to time change the terms that govern your use of our Site with effect for the future. Please read the terms carefully in advance of completing your purchase.
</p>
<h3>USE RESTRICTIONS AND COPYRIGHT LAW</h3>
<p>
	You understand and accept that all information, data, text, software, music, sound, photographs, graphics, audio, video, or other material appearing on this Site (collectively, 'Content') that are capable of being protected are owned by Forever21 or its licensors. You are expressly prohibited from using any Content without the express written consent of Forever21 or its licensors unless applicable legal provisions or principles (such as fair use or exhaustion) give you a right to use such content without consent. It is especially prohibited to reproduce, distribute, republish, download, display, post, transmit, or copy any of the material in any form or by any means, without the prior written permission of Forever21, and/or the appropriate licensor. It is admissible to copy and distribute the materials on this Site solely for personal, non-commercial use provided that all copyright and other proprietary notices contained in the materials are retained. You may not, without Forever21's express written permission; 'mirror' any material contained on this Site or any other server. Forever21 points out that any unauthorized use of any material contained on this Site may violate domestic and/or international copyright laws and the laws of privacy and publicity.
</p>
<h3>TRADEMARKS</h3>
<p>
	'FOREVER21' is a registered trademark, service mark, and/or trade name of Forever21. All other trademarks, service marks, and trade names contained in the Site are the properties of the respective owners even in case this is not explicitly indicated. Forever21 disclaims any proprietary interest in trademarks, service marks and trade names other than its own. Forever21 only uses these marks for identification purpose but not for self-promotion. No use of these marks may be made without the prior written authorization of Forever21, except as necessary to accurately identify the products or services of Forever21.
</p>
<h3>USER COMMENTS, FEEDBACK, POSTCARDS AND OTHER SUBMISSIONS</h3>
<p>
	A registered user may disclose, submit or offer to Forever 21 comments, questions, feedback, suggestions, ideas, and other submissions on or by this Site (collectively, 'Comments'). Other user may disclose, submit or offer any Comments by mail, e.g by. submit a postcard .These Comments shall be and remain Forever 21's property . The user submitting any Comments agrees to assign to Forever 21 all worldwide rights, titles and interests in all copyrights and other intellectual properties in the Comments without time restrictions. Thus, Forever 21 will own exclusively all such rights, titles and interests and shall not be limited in any way in its use, commercial or otherwise, of any Comments . Forever 21 is and shall be under no obligation (1) to maintain any Comments in confidence; (2) to pay to user any compensation for any Comments; or (3) to respond to any user Comments. 
	<br /><br />
	You agree that no Comments submitted by you to the Site will violate any right of any third party, including copyright, trademark, privacy or other personal or proprietary right(s). You further agree that no Comments submitted by you to the Site will be or contain libelous or otherwise unlawful, abusive or obscene material. You are and shall remain solely responsible for the content of any such Comments you make.
	<br /><br />
	Please see our Privacy Policy regarding any personal information you transmit to Forever21.
</p>
<h3>FOREVER 21'S COMMUNICATIONS TO YOU</h3>
<p>
	You must be registered as a registered user of the Site in order to purchase a product or to submit any Comments.
	You agree that Forever 21 may send electronic mail to you in order to fulfill the contract.
</p>
<h3>CONTENTS/PROMOTIONS</h3>
<p>
	Any contests or promotions described or posted on this Site shall be governed by the rules regulating such event or described in connection with such event.
</p>
<h3>PRODUCT AND PRICE INFORMATION</h3>
<p>
	Most Forever21 products displayed at the Site are available in select Forever21 stores while supplies last. In some cases, merchandise displayed for sale at the Site may not be available in Forever21 stores. 
	<br /><br />
	The prices displayed at the Site are quoted in Euros inclusive of VAT and are valid and effective only in the European Union.
</p>
<h3>COLORS</h3>
<p>
	We have made every effort to display, as accurately as possible, the colors of our products that appear at the Site. However, as the actual colors you see will depend on your monitor, we cannot guarantee that your monitor's display of any color will be accurate.
</p>
<h3>LINKS TO OTHER WEB SITES AND SERVICES</h3>
<p>
	To the extent that this Site contains links to outside services and resources, which Forever21 does not control, any concerns regarding any such service or resource, or any link thereto, should be directed to the particular outside service or resource.
	<br /><br />
	The following applies for every link: Forever 21 cannot influence the content, design or availability of the linked website. The use of links which connect to outside websites lays in the sole responsibility of the user.
</p>
<h3>RETENTION OF TITLE</h3>
<p>
	We retain title to the goods until receipt of all payments in full.
</p>
<h3>RETURNS</h3>
<p>
	If you are not completely satisfied with your Forever 21.com purchase, you may return it with your invoice to any Forever 21 store or by mail. Please see our Return Policy for details.
</p>
<h3>REVOCATION POLICY</h3>
<p>
	You may revoke your contractual agreement in writing (e.g. letter, fax, email) within two weeks without giving reasons for such revocation or - if the item has been sent to you prior to the expiration of the period - by returning the item. The period begins upon receipt of this declaration in writing, however not prior to the receipt of the goods by the consignee (if the same type of goods are supplied on repeated occasions, not prior to the receipt of the first consignment) and not prior to the fulfillment of our duty of information pursuant to the applicable laws. The revocation period is observed by timely sending the declaration of revocation or dispatching the item. 
	<br /><br />
The declaration of revocation shall be directed to the following address:
<br /><br />
Forever 21 E-Commerce B.V. <br />
Westbroek 64-66<br />
4822 ZW Breda<br />
The Netherlands <br />
<br /><br />
+31765480888<br />
EUcustomerservice@forever21.com
<br /><br />
The goods shall be returned to the following address: 
<br /><br />
Forever 21<br />
Leeghwaterweg 8<br />
Bergen op Zoom, 4612RD<br />
Nederland
</p>
<h3>INDEMNIFICATION</h3>
<p>
	Forever 21 shall have unrestricted liability for intentional and grossly negligent actions.
<br /><br />
In case of slight negligence Forever 21 shall be liable up to typical foreseeable damages.
<br /><br />
Limitations or exclusions of liability according to this clause shall not apply to claims based on applicable product liability laws, and to damages of life, body and health or if Forever 21 has given a guarantee of quality.
<br /><br />
If Forever 21’s liability is excluded or limited, such an exclusion or limitation shall also apply to personal liability for its employees, representatives or vicarious agents.
<br /><br />
The buyer shall indemnify Forever 21, its employees, representatives, agents and vicarious agents from any liability towards third parties, which arises from any culpable infringement of the contract by the buyer. The buyer shall compensate Forever 21 and the aforementioned persons for all necessary and reasonable costs of defense.
</p>
<h3>MISCELLANEOUS</h3>
<p>
	If any condition or part of these General Sales Conditions and Terms should be or become invalid then this shall not affect the validity of the rest of the General Sales Conditions and Terms. The invalid provision shall be replaced by a valid provision which shall be as close as possible to the spirit and purpose of the lapsed provision. The same applies in case of a regulatory gap. 
<br /><br />
Forever 21 E-Commerce B.V. <br />
Address: <br />
Westbroek 64-66 <br />
4822 ZW Breda<br />
The Netherlands <br /><br />

Chamber of Commerce registration number: 51000164
</p>
</div><!--terms -->

app/views/partials/_footer.html.erb
<div id="footer">
<ul id="footer_nav">
	<li><%= link_to "ABOUT US", about_path %></li>
	<li><%= link_to "CONTACT US", contact_path %></li>
	<li><%= link_to "FAQs", faqs_path %></li>
	<li><%= link_to "PRIVACY", privacy_path %></li>
	<li><%= link_to "TERMS", terms_path %></li>
</ul>
<%= image_tag("paypal.png", id: "paypal") %>
</div>
<p id="we">&copy; 2015 TopStore all rights reserved</p>

app/views/partials/_navigation.html.erb
<div id="nav">	
<form id="search">
		<input type="text" name="serch" id="searchf" placeholder="SEARCH" />
		<input type="submit" value="GO" id="search_btn" />
	</form>
	<span>FREE SHIPPING OVER €80</span>
	<h1 id="logo">TopStore</h1>
	
	<div id="cart">
	 	<a href="" id="sign_in">SIGN IN</a> /
		<a href="" id="sign_up">SIGN UP</a>
		<a href="<%= cart_path %>" class="cart">
			<i class="fa fa-shopping-cart"></i>
			 <%= session[:items_in_cart] %> ITEMS( S )
			€ <%= session[:total_amount] %> 
		</a>
	</div><!-- cart-->
</div><!-- nav-->
<p class="notice"><%= flash[:notice] %></p>

app/views/products/_form.html.erb
<%= form_for @product, html: {multipart: true} do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br>
    <%= f.text_field :subcategory %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>
<h1>Catalog</h1>
<br>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Price</th>
      <th>Category</th>
      <th>Subcategory</th>
      <th>Brand</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <%= link_to product.title, product %>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>

        <%= link_to (image_tag product.image_url, :style => "height:100px"), product %>

        <td><%= product.price %></td>
        <td><%= product.category %></td>
        <td><%= product.subcategory %></td>
        <td><%= product.brand %></td>
        <td><%= link_to 'Show', product %></td>
      </tr>

      <% if session[:login] == 1 %>
        <%= link_to 'Edit', edit_product_path(product) %> |
        <%= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete %>
        <% else %>
        <a href="/cart/<%= product.id %>">Add to Cart</a><br><br>
      <% end %>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @product.subcategory %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>